### ISSUE TITLE
Missing Latin Diacritics

### ISSUE THREAD

**Issue by RodneyAraujo** [hyper-type/hahmlet#9]
Hi, can you add Latin diacritics for this font? Thanks.

**Comment by Mark2Mark** [comment]
Hi. Why do you mean? This font contains all diacritics for Latin and even Latin Extended and even Vietnamese.

**Comment by ErwinDenissen** [comment]
Combining marks are missing.

**Comment by Mark2Mark** [comment]
Can you please specify instead of just throughing randomly looking statements? What exactly ios missing that you expect. Maybe something went wrong in the build process. @ErwinDenissen

**Comment by ErwinDenissen** [comment]
There are no combining diacritical marks included in the fonts. I would expect gravecomb (300), acutecomb (301), etc. On a side note, I would also expect mark-to-base and mark-to-mark lookups, but those are also missing.

**Comment by Mark2Mark** [comment]
They are present in the source but for some reason set to non-export.

**Comment by aaronbell** [comment]
@Mark2Mark I'm not quite sure I understand what you mean by `I will run a script to remove the non-export flags of all *comb glyphs outside of the GlyphsApp UI in order to feature code untouched.` 

Given that we're building from the glyphs source, wouldn't it work to just set the comb marks to exporting in the Glyphs source? That wouldn't impact the feature code, no? Or am I misunderstanding something?

**Comment by Mark2Mark** [comment]
I asked Georg, and he confirmed it might be better that way (in a text editor), otherwise the automatic feature code **_could_** in fact be affected (likely not, but: I actually tried it before coming up with that alternate approach, and saw too many changes in the diff). Hence I want to make sure that only those 'export = 0' entries are removed from the glyphs, and nothing else.

On a side note, I am really puzzled why they are set to non-export anyway. I normally don’t do that.

**Comment by aaronbell** [comment]
Interesting. Alright, I'll wait for your update.

**Comment by Mark2Mark** [comment]
Thank you so much! Will ping you, once I pushed the update :)
